apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  cluster.name: federate-cluster
  ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  ES_PLUGINS: "https://download.support.siren.io/federate/7.13.4-25.1.zip"
  http.port: "9200"
  transport.port: "9300"
  network.host: "0.0.0.0"
  cluster.initial_master_nodes: "es-master-0, es-master-1"